language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - gatsby build
deploy:
  provider: surge
  skip_cleanup: true
  domain: candicedavidson.com
  project: ./public/
on:
  branch: master
install:
  - yarn
